#!/bin/bash -e
#
# Update AucTeX auto-loads.
# 	$Id: auctex-auto-load,v 1.2 1998/01/08 13:56:25 salve Exp $	
#
# Written by Helmut Geyer <Helmut.Geyer@iwr.uni-heidelberg.de>.
# Modified by Davide G. M. Salvetti <salve@debian.org> on Tue, 30 Dec 1997 11:07:00 CET.

set -o posix

# We generate AucTeX lisp files just for GNU/Emacs, 'cause XEmacs comes with its own AucTeX.
EMACS=emacs

$EMACS -batch -q -no-site-file -l /etc/elisp/tex-site.el -f TeX-auto-generate-global

# I gues it's best to remove auto generated .el files now that .elc have been generated, in order to save some disk space.
rm -f $(find /var/lib/emacs/auctex/ -type f -name \*.el)

### Local Variables:
### mode: shell-script
### fill-column: 132
### End:
