#!/bin/bash -e
#
# postrm configuration file for Debian auctex package.
# 	$Id: postrm,v 1.2 1998/01/08 13:57:48 salve Exp $	
#
# Written by Helmut Geyer <Helmut.Geyer@iwr.uni-heidelberg.de>
# Modified by Davide G. M. Salvetti <salve@debian.org> on Tue, 30 Dec 1997 11:07:00 CET.

set -o posix

# If the package is to be removed completely, remove the info entry.
if [ "$1" != "upgrade" ] ; then
    install-info --quiet --remove auctex
    for i in /etc/xemacs/site-start-19.d /etc/emacs/site-start.d /etc/xemacs/site-start-20.d ; do
	if [ -d $i ]; then
	    cd $i
	    if [ -L ??tex-site.el ] ; then
		rm -f ??tex-site.el
	    fi
	fi
    done
fi

### Local Variables:
### mode: shell-script
### fill-column: 132
### End:
