#!/bin/bash -e
#
# postinst configuration file for Debian auctex package.
# 	$Id: postinst,v 1.2 1998/01/08 13:57:37 salve Exp $	
#
# Written by Helmut Geyer <Helmut.Geyer@iwr.uni-heidelberg.de>
# Modified by Davide G. M. Salvetti <salve@debian.org> on Tue, 30 Dec 1997 11:07:00 CET.

set -o posix

SITE_FIX=

run_auto_generate () {
    cat <<EOF
AUC TeX can parse all TeX macros packages and LaTeX style files for
information. This improves the performance of AUC TeX a lot. As this may
need a lot of time when running for the first time, you may want to run it
in the background or later by running /usr/sbin/auctex-auto-load.  If you
run it in background you will get a log file in:
    /tmp/auctex-auto-load.log
EOF
    fertig=
    until [ ! -z "$fertig" ]; do
	echo -n " Please answer run/background/later (r/b/l): "
	read answer
	case $answer in
	    r) /usr/sbin/auctex-auto-load
		fertig=j;;
	    b) /usr/sbin/auctex-auto-load > /tmp/auctex-auto-load.log 2>&1 &
		fertig=j;;
	    l) fertig=j;;
	esac
    done
}

for i in /etc/xemacs/site-start-19.d /etc/emacs/site-start.d /etc/xemacs/site-start-20.d ; do
    if [ -d $i ]; then
	cd $i
	if [ ! -L 50tex-site.el ] ; then
	    ln -s ../../elisp/tex-site.el 50tex-site.el
	fi
    fi
done

for i in /usr/lib/emacs/site-lisp/ /usr/lib/xemacs/site-lisp/ ; do
    if [ -d $i ]; then
	cd $i
	if [ ! -e tex-site.el ] ; then
	    ln -s /etc/elisp/tex-site.el .
	fi
    fi
done
     
for i in /etc/xemacs/site-start.el /etc/emacs/site-start.el /usr/lib/xemacs/site-lisp/site-start.el /usr/lib/xemacs/site-lisp/site-start-19.el /usr/lib/xemacs/site-lisp/site-start-20.el /usr/lib/emacs/site-lisp/site-start.el; do
    if [ -e $i ]; then
        if [ "`grep tex-site $i`" != "" ]; then
            SITE_FIX="$SITE_FIX $i"
        fi
    fi
done

if [ "$SITE_FIX" != "" ]; then
    echo "The following files mention tex-site.el, even though they shouldn\'t:"
    echo "  $SITE_FIX "
    echo "please remove the load or require command from these files."
    echo -n "press <return> to proceed:"
    read junk
fi

if [ "$1" = "configure" -a "$2" = "9.4g" ]; then 
    install-info --quiet --remove /usr/info/auctex.gz
    echo "Warning: tex-site.el has moved from /etc/auctex to /etc/elisp."
    run_auto_generate
fi

if [ "$1" = "configure" ]; then
    # Do we need to rebuild autos?
    if [ -d /usr/lib/emacs/common/auctex/auto/ ]; then
	# We seem to have valid autos in old location: let's move 'em to the new one if it doesn't already exist.
	if [ ! -d /var/lib/emacs/auctex/ ]; then
	    cp -a /usr/lib/emacs/common/auctex/auto/ /var/lib/emacs/auctex/ && rm -rf /usr/lib/emacs/common/auctex/auto/
	    echo "Information: auto generated files have been moved from"
	    echo "/usr/lib/emacs/common/auctex/auto/ to /var/lib/emacs/auctex/."
	    echo "You can run auctex-auto-load if you want to upgrade them, but you should"
	    echo "not need to."
	else
	    # We will assume /usr/lib/emacs/common/auctex/auto/ is stale and /var/lib/emacs/auctex/ has the right stuff into.
	    rm -rf /usr/lib/emacs/common/auctex/auto/
	    echo "Information: old /usr/lib/emacs/common/auctex/auto/ directory has been"
	    echo "removed in favor of /var/lib/emacs/auctex/."
	    echo "You can run auctex-auto-load to upgrade auto generated files in there,"
	    echo "but you should not need to."
       	fi
    elif [ ! -d /var/lib/emacs/auctex/ ]; then
	run_auto_generate
    fi
fi

install-info --quiet --section "Elisp Packages" "Elisp Packages" --menuentry="AUC TeX" --description="AUC TeX is an integrated environment for editing LaTeX and TeX files. " /usr/info/auctex.gz

### Local Variables:
### mode: shell-script
### fill-column: 132
### End:
