#!/bin/bash -e
#
# postrm configuration file for Debian auctex package.
# $Id: postrm,v 1.3 1999/10/05 22:58:36 salve Exp $
#
# Copyright © Davide G. M. Salvetti <salve@debian.org>, 1998.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to: The Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# On Debian GNU/Linux System you can find a copy of the GNU General Public
# License in /usr/share/common-licenses/GPL.

set -o posix

case "$1" in
    remove|upgrade|purge|disappear)
	if [ -x /usr/bin/update-menus ]; then update-menus; fi
    ;;
    failed-upgrade|abort-install|abort-upgrade)
	:
    ;;
    *)
	echo "${0##*/}: Called with unknown argument \`$1'." >&2
    ;;
esac

exit 0

### Local Variables:
### mode: shell-script
### End:
