#!/bin/bash -e
#
# postinst configuration file for Debian auctex package.
# $Id: postinst,v 1.21 1998/02/24 16:40:29 salve Exp $
#
# Copyright © Davide G. M. Salvetti <salve@debian.org>, 1998.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to: The Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# On Debian GNU/Linux System you can find a copy of the GNU General Public
# License in /usr/doc/copyright/GPL.

set -o posix

PACKAGE=auctex

function run_auto_generate () {
	cat <<-EOF
		AUC TeX can parse all TeX macros packages and LaTeX style files for
		information. This improves the performance of AUC TeX a lot. As this may
		need a lot of time when running for the first time, you may want to run it
		in the background or later by running /usr/sbin/update-auctex-elisp.  If
		you run it in background you will get a log file in:
		    /tmp/update-auctex-elisp.log
	EOF
	answer=
	while [ "$answer" != "r" -a "$answer" != "b" -a "$answer" != "l" ]; do
	    read -e -p "Please answer run/background/later (r/b/l): " answer
	done
	case $answer in
	    r) /usr/sbin/update-auctex-elisp;;
	    b) /usr/sbin/update-auctex-elisp &> /tmp/update-auctex-elisp.log &;;
	    l) :;;
	esac
}

# Helmut's stuff: apparently this is a workaround for a defective
# prerm|postrm in that old version.  Better to keep it.
if [ "$1" = "configure" -a "$2" = "9.4g" ]; then 
    install-info --quiet --remove /usr/info/auctex.gz
fi

case "$1" in
    configure|abort-upgrade|abort-deconfigure|abort-remove)
	/usr/lib/emacsen-common/emacs-package-install $PACKAGE
	install-info --section "Document Preparation" "Document Preparation" \
		     --menuentry="AUC TeX" \
		     --description="An integrated environment for TeX and LaTeX. " \
		     --quiet /usr/info/auctex.gz
	test -x /usr/bin/update-menus && update-menus && sleep 3
	if [ "$1" = "configure" ]; then
	    # Do we have old stuff still around?
	    for i in /usr/lib/emacs/common/auctex/auto/ /var/lib/emacs/auctex/; do
		if [ -d $i ]; then
		    # We seem to have autos in that old location: let's remove 'em.
		    rm -rf $i
		    echo "Information: old auto generated files have been removed from:"
		    echo "	$i."
		fi
	    done
	    # Do we need to rebuild autos?

	    # Since its a bit too difficult (dgms) to check if the version
	    # we are upgrading from is lower than some other version, I'll
	    # assume we do always need to rebuild autos.  After all it
	    # does no harm.
	    # Anyway, that some other version should be 9.8i-3: we changed
	    # from /var/lib/emacs/auctex to /var/lib/auctex!
	    if [ ! -d /var/lib/auctex ]; then
		run_auto_generate
	    fi
	fi
    ;;
    *)
	echo "postinst called with unknow argument \`$1'" >&2
    ;;
esac

exit 0

### Local Variables:
### mode: shell-script
### End:
