#!/bin/bash -e
#
# preinst configuration file for Debian auctex package.
# $Id: preinst,v 1.18 1998/03/06 14:51:31 salve Exp $
#
# Copyright © Davide G. M. Salvetti <salve@debian.org>, 1997, 1998.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to: The Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# On Debian GNU/Linux System you can find a copy of the GNU General Public
# License in /usr/doc/copyright/GPL.

set -o posix

function remove_handmade_auctex () {
	cat <<-EOF

		There is a locally installed version of AUC TeX in $1 which will conflict
		with this Debian package.

		Shall I:
		    1) rename its tex-site file and go on installing;
		    2) stop installing this package.

	EOF
	answer=
	while [ "$answer" != "1" -a "$answer" != "2" ]; do
	    read -e -p "Please answer (1/2, 1 recommended): " answer
	done
	if [ "$answer" = "2" ] ; then
	    exit 1
	fi
	mv -V t -b $1/tex-site.el $1/tex-site.el.dpkg-old
}

function move_old_conffile () {
	# Warn the user.
	cat <<-EOF

		There is a new method to start AUC TeX on a per user or per site basis: you
		should read /usr/doc/auctex/README.Debian.gz to learn about it.

		As a consequence of this new method, the old conffile /etc/elisp/tex-site.el
		is no more needed and will be moved to /etc/tex-site.el.old; you can safely
		remove it unless you made some change you wish to preserve.

	EOF
	mv -V t -b /etc/elisp/tex-site.el /etc/tex-site.el.old
	find /etc -name elisp -type d -empty | xargs rmdir
	# This has to be removed.
	rm -f /etc/emacs/site-start.d/50tex-site.el
}

case "$1" in
    install|upgrade)
	# Remove hand-made auctex packages from /usr/local, if existant.
	if [ -f /usr/local/lib/xemacs/site-lisp/tex-site.el ]; then
	    remove_handmade_auctex /usr/local/lib/xemacs/site-lisp/
	fi
	if [ -f /usr/local/share/emacs/site-lisp/tex-site.el ]; then
	    remove_handmade_auctex /usr/local/share/emacs/site-lisp/
	fi
	# tex-site.el is no more a conffile.
	if [ -e /etc/elisp/tex-site.el ]; then
	    move_old_conffile
	fi
    ;;
    abort-upgrade)
	:
    ;;
    *)
	echo "preinst called with unknow argument \`$1'" >&2
    ;;
esac

exit 0

### Local Variables:
### mode: shell-script
### End:
