#!/bin/bash -e
#
# Update AucTeX auto-loads.
# $Id: update-auctex-elisp,v 1.9 1998/02/22 22:32:49 salve Exp $
#
# Copyright © Davide G. M. Salvetti <salve@debian.org>, 1997, 1998.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to: The Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# On Debian GNU/Linux System you can find a copy of the GNU General Public
# License in /usr/doc/copyright/GPL.

set -o posix

# We generate AucTeX lisp files just for GNU/Emacs, 'cause XEmacs comes
# with its own AucTeX.
for FLAVOR in emacs19 emacs20; do
    if [ -x /usr/bin/$FLAVOR ]; then
	$FLAVOR -batch -q -no-site-file \
	        -l /usr/share/emacs/site-lisp/tex-site.el \
                -f TeX-auto-generate-global
    fi
done

# I gues it's better to remove auto generated .el files now that .elc have
# been generated, in order to save some disk space.
rm -f $(find /var/lib/auctex/ -type f -name \*.el)

### Local Variables:
### mode: shell-script
### End:
